
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
